<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChartOfAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
                    [
                        'id' => 1,
                        'name' => 'Assets',
                        'parent_id' => Null,
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 2,
                        'name' => 'Liability',
                        'parent_id' => Null,
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 3,
                        'name' => 'Income',
                        'parent_id' => Null,
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'in',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 4,
                        'name' => 'Expense',
                        'parent_id' => Null,
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 5,
                        'parent_id' => 1,
                        'name' => 'Current Assets',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 6,
                        'parent_id' => 1,
                        'name' => 'Fixed Assets',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 7,
                        'parent_id' => 1,
                        'name' => 'Other Assets',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 8,
                        'parent_id' => 5,
                        'name' => 'Bank',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'yes',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 9,
                        'parent_id' => 5,
                        'name' => 'Cash',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'yes',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 10,
                        'parent_id' => 5,
                        'name' => 'Inventory',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'yes',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 11,
                        'parent_id' => 5,
                        'name' => 'Accounts Receivable',
                        'status' => 'active',
                        'default_type' => 'accounts_receivable',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 12,
                        'parent_id' => 8,
                        'name' => 'Bank-123456',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'yes',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 13,
                        'parent_id' => 9,
                        'name' => 'Cash in hand',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'yes',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 14,
                        'parent_id' => 9,
                        'name' => 'Petty Cash',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 15,
                        'parent_id' => 10,
                        'name' => 'RM Inventory GL',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 16,
                        'parent_id' => 10,
                        'name' => 'FG Inventory GL',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 17,
                        'parent_id' => 10,
                        'name' => 'Cost of Production',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 18,
                        'parent_id' => 11,
                        'name' => 'Accounts Receivable GL',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 19,
                        'parent_id' => 6,
                        'name' => 'Office Equipment',
                        'status' => 'active',
                        'default_type' => 'office_equipment',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'as',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 20,
                        'parent_id' => 2,
                        'name' => 'Current Liabilities',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 21,
                        'parent_id' => 2,
                        'name' => 'Long Term Liabilities',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 22,
                        'parent_id' => 20,
                        'name' => 'Accounts Payable',
                        'status' => 'active',
                        'default_type' => 'accounts_payable',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 23,
                        'parent_id' => 20,
                        'name' => 'Taxes Payable',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 24,
                        'parent_id' => 20,
                        'name' => 'Short-Term Debt',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 25,
                        'parent_id' => 20,
                        'name' => 'Cost of Goods Sold',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 26,
                        'parent_id' => 20,
                        'name' => 'Payable to Employee',
                        'status' => 'active',
                        'default_type' => 'payable_to_employee',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],

                    [
                        'id' => 27,
                        'parent_id' => 21,
                        'name' => 'Capital',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 28,
                        'parent_id' => 21,
                        'name' => 'Notes payable',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 29,
                        'parent_id' => 21,
                        'name' => 'Long-Term Debt',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 30,
                        'parent_id' => 27,
                        'name' => 'Owners Account',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 31,
                        'parent_id' => 27,
                        'name' => 'Opening Balance of Equity',
                        'status' => 'active',
                        'default_type' => 'oboe',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 32,
                        'parent_id' => 27,
                        'name' => 'Retained Earning',
                        'status' => 'active',
                        'default_type' => 'retained_earning',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 33,
                        'parent_id' => 3,
                        'name' => 'Sales',
                        'status' => 'active',
                        'default_type' => 'sales',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'in',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 34,
                        'parent_id' => 3,
                        'name' => 'Others',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'in',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 35,
                        'parent_id' => 33,
                        'name' => 'Revenue from sales',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'in',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 36,
                        'parent_id' => 4,
                        'name' => 'Direct Expenses',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 37,
                        'parent_id' => 4,
                        'name' => 'Indirect Expenses',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 38,
                        'parent_id' => 4,
                        'name' => 'Advertising Expense',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 39,
                        'parent_id' => 4,
                        'name' => 'Cost of Goods Sold',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 40,
                        'parent_id' => 36,
                        'name' => 'Utility',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 41,
                        'parent_id' => 40,
                        'name' => 'Water Bill',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 42,
                        'parent_id' => 40,
                        'name' => 'Electricity Bill',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 43,
                        'parent_id' => 39,
                        'name' => 'Cost of Goods Sold GL',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'ledger',
                        'account_type' => 'debit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'ex',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 44,
                        'parent_id' => 2,
                        'name' => 'External Liabilities',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 45,
                        'parent_id' => 2,
                        'name' => 'Internal Liabilities',
                        'status' => 'active',
                        'default_type' => '',
                        'type' => 'group',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 46,
                        'parent_id' => 45,
                        'name' => 'Owners Equity',
                        'status' => 'active',
                        'default_type' => 'accounts_payable',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],
                    [
                        'id' => 47,
                        'parent_id' => 45,
                        'name' => 'Opening balance of Equity',
                        'status' => 'active',
                        'default_type' => 'accounts_payable',
                        'type' => 'ledger',
                        'account_type' => 'credit',
                        'is_bank_cash' => 'no',
                        'root_account_type' => 'li',
                        'created_at' => Carbon::now(),
                    ],

                ];
        DB::table('chart_of_accounts')->insert($data);
    }
}
