version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: erp
        container_name: erp
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/custom.ini:/usr/local/etc/php/conf.d/php-overrides.ini
        networks:
            - erp-app-network
        ports:
            - "9001:9000"

    nginx:
        image: nginx:alpine
        container_name: erp-nginx
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - erp-app-network

networks:
    erp-app-network:
        driver: bridge
