<?php

return [
    'RM' => [
        [
            'id' => 5,
            'parent_id' => 1,
            'name' => 'Cake',
            'type' => 'group',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 6,
            'parent_id' => 1,
            'name' => 'Fast Food',
            'type' => 'group',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 7,
            'parent_id' => 1,
            'name' => 'Bakery',
            'type' => 'group',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 8,
            'parent_id' => 1,
            'name' => 'Others',
            'type' => 'group',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 9,
            'parent_id' => 5,
            'name' => 'Chocolate',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 10,
            'parent_id' => 5,
            'name' => 'Premix',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],

        [
            'id' => 11,
            'parent_id' => 5,
            'name' => 'Vivo Cream',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 12,
            'parent_id' => 5,
            'name' => 'Chesse',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 13,
            'parent_id' => 5,
            'name' => 'Egg',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 14,
            'parent_id' => 5,
            'name' => 'Cooking Oil',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 15,
            'parent_id' => 5,
            'name' => 'Butter',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 16,
            'parent_id' => 5,
            'name' => 'Nut',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 17,
            'parent_id' => 5,
            'name' => 'Rice',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 18,
            'parent_id' => 5,
            'name' => 'Condensed Milk',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 19,
            'parent_id' => 5,
            'name' => 'Coconut Milk',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 20,
            'parent_id' => 5,
            'name' => 'Fritet mix',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 21,
            'parent_id' => 5,
            'name' => 'Kismis',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 22,
            'parent_id' => 5,
            'name' => 'Lecture Glucose',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 23,
            'parent_id' => 5,
            'name' => 'Fondent',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 24,
            'parent_id' => 5,
            'name' => 'Conflour',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 25,
            'parent_id' => 5,
            'name' => 'Sugar',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 26,
            'parent_id' => 5,
            'name' => 'Flour',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 27,
            'parent_id' => 5,
            'name' => 'Food Colour',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 28,
            'parent_id' => 5,
            'name' => 'Colour past',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 29,
            'parent_id' => 5,
            'name' => 'Ghee',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 30,
            'parent_id' => 5,
            'name' => 'Paping Gel',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 31,
            'parent_id' => 5,
            'name' => 'Gel-(mango,blueberry,Strawberry)',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 32,
            'parent_id' => 5,
            'name' => 'Pulp-(mango,blueberry,Strawberry)',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 33,
            'parent_id' => 5,
            'name' => 'Coffee Powder',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 34,
            'parent_id' => 5,
            'name' => 'Oreo Biscuit',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 35,
            'parent_id' => 5,
            'name' => 'Powder Milk',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 36,
            'parent_id' => 5,
            'name' => 'Color Rice',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 37,
            'parent_id' => 5,
            'name' => 'Chocolate Chips',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 38,
            'parent_id' => 5,
            'name' => 'Chocolate Ganache',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 39,
            'parent_id' => 5,
            'name' => 'Suger Butterfly',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 40,
            'parent_id' => 5,
            'name' => 'Golden/Silver dust',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 41,
            'parent_id' => 5,
            'name' => 'Golden/Silver Foil',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 42,
            'parent_id' => 5,
            'name' => 'Cake Belt',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 43,
            'parent_id' => 5,
            'name' => 'Pastry Raper poly',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 44,
            'parent_id' => 5,
            'name' => 'Cake Sticker',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 45,
            'parent_id' => 5,
            'name' => 'Cake & Pastry Logo',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 46,
            'parent_id' => 5,
            'name' => 'Suger Paper-A4/A3',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 47,
            'parent_id' => 6,
            'name' => 'Chicken',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],

        [
            'id' => 48,
            'parent_id' => 6,
            'name' => 'Soy Sauce',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 49,
            'parent_id' => 6,
            'name' => 'Tomato Sauce',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 50,
            'parent_id' => 6,
            'name' => 'Oyster Sauce',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 51,
            'parent_id' => 6,
            'name' => 'Mayonnaise',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 52,
            'parent_id' => 6,
            'name' => 'Slice Chesse',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 53,
            'parent_id' => 6,
            'name' => 'Pum Oil',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 54,
            'parent_id' => 6,
            'name' => 'Cooking Oil',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 55,
            'parent_id' => 6,
            'name' => 'Vegetable',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 56,
            'parent_id' => 6,
            'name' => 'Flour',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 57,
            'parent_id' => 6,
            'name' => 'Maslas',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 58,
            'parent_id' => 7,
            'name' => 'Dalda',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 59,
            'parent_id' => 7,
            'name' => 'Yeast',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 60,
            'parent_id' => 8,
            'name' => 'Oil Paper',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 61,
            'parent_id' => 8,
            'name' => 'A4 Paper',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 62,
            'parent_id' => 8,
            'name' => 'Art Paper',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 63,
            'parent_id' => 8,
            'name' => 'Newsprint Paper',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 64,
            'parent_id' => 8,
            'name' => 'Pastry Cases',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 65,
            'parent_id' => 8,
            'name' => 'Stationery',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 66,
            'parent_id' => 8,
            'name' => 'Gadgets-(Pen Drive,M)',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
        [
            'id' => 67,
            'parent_id' => 8,
            'name' => 'Printer ink',
            'type' => 'item',
            'rootAccountType' => 'RM',
        ],
    ],
    'FG' => [
        [
            'id' => 68,
            'parent_id' => 3,
            'name' => 'Display Cake',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 69,
            'parent_id' => 3,
            'name' => 'Pastry Cake',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 70,
            'parent_id' => 3,
            'name' => 'Fast Food',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 71,
            'parent_id' => 3,
            'name' => 'Bakery Item',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 72,
            'parent_id' => 3,
            'name' => 'Cookies',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 73,
            'parent_id' => 3,
            'name' => 'Drinks & Birthday Item',
            'type' => 'group',
            'rootAccountType' => 'FG',
        ],
        [
            'id' => 74,
            'parent_id' => 68,
            'name' => 'Vanilla',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 1000,
        ],
        [
            'id' => 75,
            'parent_id' => 68,
            'name' => 'Normal Chocolate',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 76,
            'parent_id' => 68,
            'name' => 'Special Chocolate',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 77,
            'parent_id' => 68,
            'name' => 'Black Forest',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 78,
            'parent_id' => 68,
            'name' => 'Straw berry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 79,
            'parent_id' => 68,
            'name' => 'Mango',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 80,
            'parent_id' => 68,
            'name' => 'Cheese Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 81,
            'parent_id' => 68,
            'name' => 'Red Velvet',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 82,
            'parent_id' => 68,
            'name' => 'Rain Bow Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 83,
            'parent_id' => 73,
            'name' => 'Cap-40',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 84,
            'parent_id' => 73,
            'name' => 'Cap-50',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 85,
            'parent_id' => 68,
            'name' => 'Choco-Vanilla',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 200,
        ],
        [
            'id' => 86,
            'parent_id' => 68,
            'name' => 'Marble Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 800,
        ],
        [
            'id' => 87,
            'parent_id' => 68,
            'name' => 'White Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 800,
        ],
        [
            'id' => 88,
            'parent_id' => 68,
            'name' => 'V.Mousse',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 800,
        ],
        [
            'id' => 89,
            'parent_id' => 68,
            'name' => 'Cho. Mousse',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 800,
        ],
        [
            'id' => 90,
            'parent_id' => 68,
            'name' => 'Tira Mousse',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 800,
        ],
        [
            'id' => 91,
            'parent_id' => 68,
            'name' => 'Brownie',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 560,
        ],
        [
            'id' => 92,
            'parent_id' => 68,
            'name' => 'Chocolate Ball',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 560,
        ],
        [
            'id' => 93,
            'parent_id' => 68,
            'name' => 'Chocolate Roll',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 560,
        ],
        [
            'id' => 94,
            'parent_id' => 68,
            'name' => 'V.Swiss Roll',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 560,
        ],
        [
            'id' => 95,
            'parent_id' => 68,
            'name' => 'Cho. Swiss Roll',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 560,
        ],
        [
            'id' => 96,
            'parent_id' => 69,
            'name' => 'Vanilla Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 450,
        ],

        [
            'id' => 97,
            'parent_id' => 69,
            'name' => 'Non Chocolate Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 450,
        ],

        [
            'id' => 98,
            'parent_id' => 69,
            'name' => 'Black Forest Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 450,
        ],

        [
            'id' => 99,
            'parent_id' => 69,
            'name' => 'Lava Muffin',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 450,
        ],

        [
            'id' => 100,
            'parent_id' => 69,
            'name' => 'Strawberry Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 450,
        ],

        [
            'id' => 101,
            'parent_id' => 69,
            'name' => 'Mango Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 102,
            'parent_id' => 69,
            'name' => 'Blackberry Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 103,
            'parent_id' => 69,
            'name' => 'Mango Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 104,
            'parent_id' => 69,
            'name' => 'Cheese Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 105,
            'parent_id' => 69,
            'name' => 'Red Velvet Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 106,
            'parent_id' => 69,
            'name' => 'Rain Bow Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 107,
            'parent_id' => 69,
            'name' => 'Coffee Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 108,
            'parent_id' => 69,
            'name' => 'Moist Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],

        [
            'id' => 109,
            'parent_id' => 69,
            'name' => 'Caramel Pastry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 510,
        ],
        [
            'id' => 110,
            'parent_id' => 70,
            'name' => 'Arabian Finni',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 111,
            'parent_id' => 70,
            'name' => 'Chicken Pizza',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 112,
            'parent_id' => 70,
            'name' => 'Slice Pizza',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 113,
            'parent_id' => 70,
            'name' => 'Chicken burger',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 114,
            'parent_id' => 70,
            'name' => 'Chicken Reshmi Burger',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 115,
            'parent_id' => 70,
            'name' => 'Chichen Cheese Burger',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 116,
            'parent_id' => 70,
            'name' => 'Chicken Shawrma (Crispy)',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 117,
            'parent_id' => 70,
            'name' => 'Chicken Shawarma (Barbeque)',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 118,
            'parent_id' => 70,
            'name' => 'Chicken Sandwich',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 119,
            'parent_id' => 70,
            'name' => 'Chicken Roll',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 220,
        ],
        [
            'id' => 120,
            'parent_id' => 70,
            'name' => 'Chicken Petties Roll',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 180,
        ],
        [
            'id' => 121,
            'parent_id' => 70,
            'name' => 'Chicken Russian Petties',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 180,
        ],
        [
            'id' => 122,
            'parent_id' => 70,
            'name' => 'HotDog (Kima)',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 180,
        ],
        [
            'id' => 123,
            'parent_id' => 70,
            'name' => 'Vanilla Donat',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 180,
        ],
        [
            'id' => 124,
            'parent_id' => 70,
            'name' => 'Chocolate Donat',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 180,
        ],
        [
            'id' => 125,
            'parent_id' => 70,
            'name' => 'Chicken Samucha',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 126,
            'parent_id' => 70,
            'name' => 'Pudin',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 127,
            'parent_id' => 71,
            'name' => 'Family Bread Mini',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 128,
            'parent_id' => 71,
            'name' => 'Family Bread Large',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 129,
            'parent_id' => 71,
            'name' => 'Milk Bread Mini',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 130,
            'parent_id' => 71,
            'name' => 'Cream Bun',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 131,
            'parent_id' => 71,
            'name' => 'Lemon Bun',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 132,
            'parent_id' => 71,
            'name' => 'Vanilla Butter Bun',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 133,
            'parent_id' => 71,
            'name' => 'Chocolate Butter Bun',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 134,
            'parent_id' => 71,
            'name' => 'Plane Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 135,
            'parent_id' => 71,
            'name' => 'Ovaltine Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 136,
            'parent_id' => 71,
            'name' => 'Fruit Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 137,
            'parent_id' => 71,
            'name' => 'Sweet Toast',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 138,
            'parent_id' => 71,
            'name' => 'Tea Toast Mini',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 139,
            'parent_id' => 71,
            'name' => 'Gurlic Toast',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 40,
        ],
        [
            'id' => 140,
            'parent_id' => 72,
            'name' => 'Ovaltine Cookies',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 141,
            'parent_id' => 72,
            'name' => 'Elmond Nut Cookies',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 142,
            'parent_id' => 72,
            'name' => 'Penut Cookies',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 143,
            'parent_id' => 72,
            'name' => 'Milk Kachcha',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 144,
            'parent_id' => 72,
            'name' => 'Nut Cookies',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 145,
            'parent_id' => 72,
            'name' => 'Dry Cake',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 146,
            'parent_id' => 72,
            'name' => 'Baby Sweet Toast',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 147,
            'parent_id' => 72,
            'name' => 'Sweet Toast',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 148,
            'parent_id' => 72,
            'name' => 'Salt',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 149,
            'parent_id' => 72,
            'name' => 'Penut',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 150,
            'parent_id' => 72,
            'name' => 'Elmond Nut',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 151,
            'parent_id' => 72,
            'name' => 'Semai',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 60,
        ],
        [
            'id' => 152,
            'parent_id' => 72,
            'name' => 'Jelly',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 153,
            'parent_id' => 72,
            'name' => 'Panir',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 154,
            'parent_id' => 72,
            'name' => 'Chocolate Mimi',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 155,
            'parent_id' => 72,
            'name' => 'Brown',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 156,
            'parent_id' => 72,
            'name' => 'Cherry',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 157,
            'parent_id' => 72,
            'name' => 'Chocolate Cookies',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 158,
            'parent_id' => 72,
            'name' => 'Swich Pop',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 70,
        ],
        [
            'id' => 159,
            'parent_id' => 73,
            'name' => '200 ML Glass Coac',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 160,
            'parent_id' => 73,
            'name' => '500 Ml Water',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 161,
            'parent_id' => 73,
            'name' => 'SP Baloon',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 162,
            'parent_id' => 73,
            'name' => 'Foam Snow-Spary',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 163,
            'parent_id' => 73,
            'name' => 'Foyel Baloon',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 164,
            'parent_id' => 73,
            'name' => 'Party Poper',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 165,
            'parent_id' => 73,
            'name' => 'Number Mom',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 166,
            'parent_id' => 73,
            'name' => 'Stick Mom',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 167,
            'parent_id' => 73,
            'name' => 'Banner',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 168,
            'parent_id' => 73,
            'name' => 'Foil B.Banner',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 169,
            'parent_id' => 73,
            'name' => 'Coffee Cup',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 170,
            'parent_id' => 73,
            'name' => 'Cap-20',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 171,
            'parent_id' => 73,
            'name' => 'Arabian',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
        [
            'id' => 172,
            'parent_id' => 73,
            'name' => 'Cap-30',
            'type' => 'item',
            'rootAccountType' => 'FG',
            'unit_id' => 3,
            'price' => 120,
        ],
    ]
];
